name: cellcounter
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  # - bioconda::fiji
  # GPU acceleration (only CuPy from conda works)
  # - cuda-toolkit
  # - cupy
  - pip:
      # - cellcounter[gpu,elastix]
      - -e ".[gpu,elastix]"
