[project]
name = "cellcounter"
version = "0.1.0"
description = "cFos cell counting and region mapping for whole brain microscopy"
authors = [{ name = "BowenLab" }]
requires-python = ">=3.12"
readme = "README.md"
license = "GNU GPLv3"
dependencies = [
    "jinja2>=3.1.5,<4",
    "streamlit>=1.41.1,<2",
    "tifffile>=2025.1.10,<2026",
    "numpy>=1.26.4,<2",
    "pandas>=2.2.3,<3",
    "seaborn>=0.13.2,<0.14",
    "scikit-image>=0.25.0,<0.26",
    "zarr>=3.0.0,<4",
    "dask[complete]>=2024.11.2,<2025",
    "graphviz>=0.20.3,<0.21",
    "natsort>=8.4.0,<9",
    "napari[all]>=0.5.5,<0.6",
    "pydantic>=2.10.5,<3",
    "nibabel>=5.3.2,<6",
]

[project.optional-dependencies]
gpu = ["dask-cuda>=24.12.0,<25"]
elastix = ["simpleitk-simpleelastix>=2.4.0.dev53,<3"]

[project.urls]
Homepage = "https://tlee08.github.io/cellcounter"
Repository = "https://github.com/tlee08/cellcounter"
Documentation = "https://tlee08.github.io/cellcounter"

[project.scripts]
cellcounter_init = "cellcounter.scripts.init:main"
cellcounter_project_gui = "cellcounter.scripts.project_gui:run_script"
cellcounter_make_project = "cellcounter.scripts.make_project:main"

[dependency-groups]
dev = [
    "ruff>=0.4.8,<0.5",
    "mkdocs-material>=9.5.18,<10",
    "mkdocstrings-python>=1.9.2,<2",
    "pytest>=8.3.3,<9",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 120

[tool.ruff.format]
docstring-code-format = true
